flags: {}
user-message: ! 'Warning: Specified resolver could not satisfy all dependencies. Some
  external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- '.'
extra-deps:
- http-types-0.8.6
- scotty-0.9.1
- scotty-hastache-0.2.1
- text-1.2.2.0
- wai-3.0.3.0
- warp-3.0.13.1
resolver: lts-5.8
