flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- BoundedChan-1.0.3.0
- HUnit-1.2.5.2
- QuickCheck-2.8.2
- aeson-0.9.0.1
- ansi-terminal-0.6.2.3
- appar-0.1.4
- async-2.1.0
- attoparsec-0.13.0.1
- auto-update-0.1.2.2
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- bytestring-lexing-0.5.0.2
- case-insensitive-1.2.0.5
- cookie-0.4.1.6
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- directory-1.2.4.0
- dlist-0.7.1.2
- easy-file-0.2.1
- exceptions-0.8.0.2
- fast-logger-2.4.1
- filepath-1.3.0.1
- hashable-1.2.3.3
- hastache-0.6.1
- hedis-0.6.9
- hspec-2.0.2
- hspec-core-2.0.2
- hspec-discover-2.0.2
- hspec-expectations-0.6.1.1
- http-date-0.0.6.1
- http-types-0.8.6
- ieee754-0.7.6
- iproute-1.7.0
- lifted-base-0.2.3.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- nats-1
- network-2.6.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- primitive-0.6.1.0
- process-1.4.0.0
- quickcheck-io-0.1.2
- random-1.0.1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.1.6
- scientific-0.3.4.2
- scotty-0.9.1
- scotty-hastache-0.2.1
- semigroups-0.18
- setenv-0.1.1.3
- simple-sendfile-0.2.21
- stm-2.4.4
- streaming-commons-0.1.14.2
- stringsearch-0.3.6.6
- syb-0.6
- tagged-0.8.1
- text-1.2.1.3
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.6
- unordered-containers-0.2.5.1
- vault-0.3.0.4
- vector-0.11.0.0
- void-0.7.1
- wai-3.0.3.0
- wai-extra-3.0.14
- wai-logger-2.2.4.1
- wai-middleware-static-0.6.0.1
- warp-3.0.13.1
- word8-0.1.2
- zlib-0.6.1.1
resolver: ghc-7.10
